// Text("Name :$name3 "),
//                 Text("Email:$email3"),
//                 Text("Phone Number:$phonenumber3"),
//                 Text("Gender:$selectedGender3"),
//                 Text("Degree:$degree3"),
//                 Text("Collage$college3"),
//                 Text("Skill:$skill3"),
//                 Text("Skill Level:$skilllevel3"),
//                 Text("Job:$job3"),
//                 Text("City:$jobcity3"),
//                 Text("Organization:$organization3"),
//                 Text("Description:$description3"),
//                 Text("Work End Date:$startDateWork"),
//                 Text("Work End Date:$endDateWork"),
//                 Text("clz End Date:$edustartdate3"),
//                 Text("clz End Date:$eduenddate3"),
//                 Text("Languagr:$language"),
//                 Text("Hobbies:$hobbies"),