  //  Text("${widget.name2}"),
  //           Text("${widget.address2}"),
  //           Text("${widget.phonenumber2}"),
  //           Text("${widget.selectedGender2}"),
  //           Text("${widget.college2}"),
  //           Text("${widget.degree2}"),
  //           Text("${widget.collagedate2}"),
  //           Text("${widget.skill2}"),
  //           Text("${widget.skilllevel2}"),
  //           // Text("${widget.name2}"),